# Generated by Django 4.0.1 on 2022-03-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rhythmic', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=16)),
                ('paragraphs', models.CharField(max_length=9999)),
                ('title_rank_baidu', models.IntegerField()),
                ('title_rank_bing', models.IntegerField()),
                ('rhythmic_rank_baidu', models.IntegerField()),
                ('rhythmic_rank_bing', models.IntegerField()),
            ],
        ),
    ]
