# Generated by Django 4.0.1 on 2022-03-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetry',
            name='rhythmic_rank_baidu',
        ),
        migrations.RemoveField(
            model_name='poetry',
            name='rhythmic_rank_bing',
        ),
        migrations.RemoveField(
            model_name='poetry',
            name='title_rank_baidu',
        ),
        migrations.RemoveField(
            model_name='poetry',
            name='title_rank_bing',
        ),
    ]
