# Generated by Django 4.0.1 on 2022-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_poetry_author_remove_poetry_paragraphs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='author',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='poetry',
            name='paragraphs',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='poetry',
            name='rhythmic',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
